<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/13/16
 * Time: 12:11 PM
 */

$_product = Mage::registry('current_product');
$_helper = $this->helper('catalog/output');
$_currentDate = Mage::getModel('core/date')->date('Y-m-d H:i:s');
?>
<div class="label-product clearfix">
    <?php if ($_product->getData('news_from_date') && strtotime($_currentDate) > strtotime($_product->getData('news_from_date'))): ?>
        <span type="button" class="label-span label-yellow"><?php echo $this->__('New');?></span>
    <?php endif; ?>
    <?php if ($_product->getData('sale')): ?>
        <span type="button" class="label-span label-primary"><?php echo $this->__('Sale');?></span>
    <?php endif; ?>
    <?php if ($_product->getData('promo')): ?>
        <span type="button" class="label-span label-yellow-light"><?php echo $this->__('Promo');?></span>
    <?php endif; ?>
    <?php if ($_product->getData('out_of_production') || true): ?>
        <span type="button" class="label-span label-grey"><?php echo $this->__('Out of production');?></span>
    <?php endif; ?>
</div>
