<?php
/** @var $this Smasoft_Oneclickorder_Block_Form */
/** @var $helper Smasoft_Oneclickorder_Helper_Data */
$helper = Mage::helper('smasoft_oneclickorder');
$action = $this->getAction()->getFullActionName();

?>
<div class="btn yellow btn-lg btn-width border-radius-none bold margin-top-min" data-toggle="modal" href="#one_click_order"><?php echo $this->__('Proceed to Checkout')?></div>

<div class="modal fade draggable-modal" id="one_click_order" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog  modal-sm">
        <div class="modal-content">
            <div id="oneclickorder-form-wrapper" class="<?php echo $this->getAction()->getFullActionName()?>">
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    <h4 class="modal-title text-center"><?php echo $this->__('Place Order')?></h4>
                </div>
                <div class="modal-body modal-body-form text-left">
                    <form id="oneclickorder-form" action="<?php echo $this->getUrl('oneclickorder/index/saveOrder')?>" method="post">
                        <div class="oneclickorder-fields">
                            <div class="form-group select-content">
                                 <?php echo $this->getPhoneCodeHtml('oneclickorder[country]', 'form-control radius-none validate-select oneclickorder-country', true, $helper->__('Code'))?>
                                <input type="text" name="oneclickorder[phone]" class="form-control radius-none  required-entry oneclickorder-phone"  placeholder="<?php echo $this->__('phone number')?>"/>
                            </div>
                            <div class="form-group">
                                <?php if ($this->isShowEmailField()): ?>
                                <input type="text" name="oneclickorder[email]" class="form-control radius-none required-entry validate-email oneclickorder-email"  placeholder="<?php echo $this->__('email')?>"/>
                                <?php endif; ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label"><?php echo $helper->__('Comment:')?>:</label>
                                <textarea class="form-control radius-none" name="oneclickorder[comment]"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="button-wrapper" id="oneclickorder-buttons-container">
                                <button type="button" class=" text-center btn yellow margin-top-min min-width <?php echo $action=='checkout_cart_index' ? 'btn-proceed-checkout btn-checkout' : ''?>" name="submitOneclickOrder" onclick="oneClickOrder.saveOrder()"/>
                                    <span><span><?php echo $this->__('Order Now')?></span></span>
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <p class="txt-sm"><span class="has-span">*</span><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('one_click_order_notice')->toHtml();?></p>
                        </div>
                        <span class="please-wait" id="oneclickorder-please-wait" style="display:none;">
                            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $helper->__('Submit Order...') ?>" title="<?php echo $helper->__('Submit Order...') ?>" class="v-middle" /> <?php echo $helper->__('Submit Order...') ?>
                        </span>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">



    var oneClickOrder = {
        formInstance:new VarienForm('oneclickorder-form'),

        _processResponse:function (response) {
            if (response.error) {
                Element.hide('oneclickorder-please-wait');
                Element.show('oneclickorder-buttons-container');
                $('oneclickorder-buttons-container').descendants().each(function(s) {
                    s.disabled = false;
                });
                alert(response.error);
                return false;
            }
            if (response.success) {
                if (response.message) {
                    alert(response.message)
                }
                if (response.redirect) {
                    window.location.href = response.redirect;
                }
            }
            return true;
        },
        _afterSaveOrder:function (transport) {
            var response = {};
            try {
                response = transport.responseText.evalJSON();
            } catch (e) {
                response = transport.responseText;
            }
            if (this._processResponse(response)) {

            }
        },
        saveOrder:function () {
            if(agreementsForm.validator && !agreementsForm.validator.validate()){
                    $('#one_click_order').hide();
                }

            if (this.formInstance.validator && this.formInstance.validator.validate()) {

                Element.show('oneclickorder-please-wait');
                Element.hide('oneclickorder-buttons-container');
                $('oneclickorder-buttons-container').descendants().each(function(s) {
                    s.disabled = true;
                });

                new Ajax.Request(this.formInstance.form.getAttribute('action'), {
                    method:'post',
                    parameters:this.formInstance.form.serialize(),
                    onComplete:this._afterSaveOrder.bind(this),
                    onFailure:function () {
                        location.href = BASE_URL;
                    }
                });
            }
        }
    };

</script>