<?php
/** @var $this Smasoft_Oneclickorder_Block_Form */
/** @var $helper Smasoft_Oneclickorder_Helper_Data */
$helper = Mage::helper('smasoft_oneclickorder');
$action = $this->getAction()->getFullActionName();

?>
<div class="btn yellow-mint btn-outline min-width" data-toggle="modal" href="#one_click_order">Оформить заказ</div>

<div class="modal fade draggable-modal" id="one_click_order" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="oneclickorder-form-wrapper" class="<?php echo $this->getAction()->getFullActionName()?>">
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                </div>
                <div class="modal-body modal-body-form">
                    <div class="descr">
                        <p><?php echo $this->__('1 Click Order')?></p>
                        <p><?php echo $this->__('Manager will call you, knows all details and will help place your order.')?></p>
                    </div>
                    <form id="oneclickorder-form" action="<?php echo $this->getUrl('oneclickorder/index/saveOrder')?>" method="post">
                        <div class="oneclickorder-fields">
                            <img class="phone-icon" src="<?php echo $this->getSkinUrl('images/oneclickorder/telephone.png') ?>"/>
                            <?php echo $this->getPhoneCodeHtml('oneclickorder[country]', 'validate-select oneclickorder-country', true, $helper->__('Code'))?>
                            <input type="text" name="oneclickorder[phone]" class="form-control radius-none  required-entry oneclickorder-phone"  placeholder="<?php echo $this->__('phone number')?>"/>

                            <div class="form-group">
                                <?php if ($this->isShowEmailField()): ?>
                                <input type="text" name="oneclickorder[email]" class="form-control radius-none required-entry validate-email oneclickorder-email"  placeholder="<?php echo $this->__('email')?>"/>
                                <?php endif; ?>
                            </div>
                            <div class="form-group comment-wrapper" id="oneclickorder-comment-wrapper" style="display: none;">
                                <label class="control-label"><?php echo $helper->__('Comment:')?></label>
                                <textarea class="form-control radius-none" name="oneclickorder[comment]"></textarea>
                            </div>
                        </div>
                        <div class="button-wrapper" id="oneclickorder-buttons-container">
                            <div class="comment-toggle" title="<?php echo $this->__('Add comment')?>">&nbsp;</div>
                            <button type="button" class="btn yellow margin-top-min min-width <?php echo $action=='checkout_cart_index' ? 'btn-proceed-checkout btn-checkout' : ''?>" name="submitOneclickOrder" onclick="oneClickOrder.saveOrder()"/>
                                <span><span><?php echo $this->__('Order Now')?></span></span>
                            </button>
                        </div>
                        <span class="please-wait" id="oneclickorder-please-wait" style="display:none;">
                            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $helper->__('Submit Order...') ?>" title="<?php echo $helper->__('Submit Order...') ?>" class="v-middle" /> <?php echo $helper->__('Submit Order...') ?>
                        </span>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    var oneClickOrder = {
        formInstance:new VarienForm('oneclickorder-form'),

        _processResponse:function (response) {
            if (response.error) {
                Element.hide('oneclickorder-please-wait');
                Element.show('oneclickorder-buttons-container');
                $('oneclickorder-buttons-container').descendants().each(function(s) {
                    s.disabled = false;
                });
                alert(response.error);
                return false;
            }
            if (response.success) {
                if (response.message) {
                    alert(response.message)
                }
                if (response.redirect) {
                    window.location.href = response.redirect;
                }
            }
            return true;
        },
        _afterSaveOrder:function (transport) {
            var response = {};
            try {
                response = transport.responseText.evalJSON();
            } catch (e) {
                response = transport.responseText;
            }
            if (this._processResponse(response)) {

            }
        },
        saveOrder:function () {
            if (this.formInstance.validator && this.formInstance.validator.validate()) {

                Element.show('oneclickorder-please-wait');
                Element.hide('oneclickorder-buttons-container');
                $('oneclickorder-buttons-container').descendants().each(function(s) {
                    s.disabled = true;
                });

                new Ajax.Request(this.formInstance.form.getAttribute('action'), {
                    method:'post',
                    parameters:this.formInstance.form.serialize(),
                    onComplete:this._afterSaveOrder.bind(this),
                    onFailure:function () {
                        location.href = BASE_URL;
                    }
                });
            }
        },
        toggleCommentBlock:function (event) {
            Element.toggle('oneclickorder-comment-wrapper');
        }
    };

    $$("#oneclickorder-form-wrapper .comment-toggle").invoke('observe', 'click', function () {
        oneClickOrder.toggleCommentBlock(this)
    });

</script>