<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">
    <p class="block-subtitle"><?php echo $this->__('Filtered By') ?></p>
    <ol>
    <?php foreach ($_filters as $_filter): ?>
        <li>
        	<div class="active-filter-wrapper">
        	<?php $vals = explode("_",$_filter->getValue()); ?>
			
        	<?php if(count($vals) > 1): ?>
        		<?php $filterVal = ''; foreach($vals as $val): ?>   
        			<?php $filterVals = $_filter->getFilter()->getFIlterAppliedValues(); $filterOptions = $_filter->getFilter()->getFilterOptionValues() ?>
        			<?php $filterVal .= $filterOptions[$val] . ", "; ?>
        		<?php endforeach; ?>
            	<span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <span class="value"><?php echo substr(trim($filterVal), 0, -1) ?></span>
        	<?php else: ?>
            	<span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
            <?php endif; ?>
            <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                if ($clearLinkUrl):
            ?>
                <a  class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>"><?php echo $this->__('Previous') ?></a>
                <a  class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
            <?php else: ?>
                <a  class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove This Item') ?></a>
            <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
