<?php if($this->canShowBlock()): ?>

<div class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
<?php if(Mage::registry('current_category')->getLevel() == 3): ?>

    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <div id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount() > 0): ?>
                    <div class="type-checkbox clearfix" >
                        <span class="type-title"><?php echo $this->__($_filter->getName()) ?>:</span>                  
                        <div class="display-filter"><?php $_filter->setTemplate('mkmage/layerednavigation/filter.phtml'); echo $_filter->getHtml() ?></div>
                    </div>
                <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
<?php endif ?>
</div>
<?php endif; ?>


