<?php
/**
 * Mageplaza_BetterBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post Tag list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 */
?>
<?php $_tags = $this->getTags(); ?>
<?php if ($_tags->getSize() > 0) : ?>
    <div class="block">
        <p class="text-transform"><?php echo Mage::helper('mageplaza_betterblog')->__('Tags') ?></p>
        <ul class="ul-outside">
            <?php foreach ($_tags as $_tag) : ?>
                <li>              
                    <a href="<?php echo $_tag->getTagUrl() ?>">
                        <?php echo $_tag->getName(); ?>
                    </a>
                </li> 
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
