<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/11/16
 * Time: 2:18 PM
 */?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <div class="type-content">
        <div class="type-radio">
            <span class="type-title"><?php echo $this->__('Sort By') ?></span>
            <div class="left-content">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <div class="radio-group">
                        <label><?php echo $this->__($_order) ?></label>
                        <a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>" class="checkbox-label"><?php echo $this->__('ASC') ?></a>
                        <a href="<?php echo $this->getOrderUrl($_key, 'desc') ?>" class="checkbox-label"><?php echo $this->__('DESC') ?></a>
                    </div>
            <?php endforeach; ?>
            </div>
        </div>
        <div class="pager">
            <div class="count-container">
                <?php if($this->getLastPageNum()>1): ?>
                    <p class="amount amount--has-pages">
                        <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                    </p>
                <?php else: ?>
                    <p class="amount amount--no-pages">
                        <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                    </p>
                <?php endif; ?>

                <div class="limiter">
                    <label><?php echo $this->__('Show') ?></label>
                    <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
                        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                                <?php echo $_limit ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <?php echo $this->getPagerHtml() ?>

        </div>
    </div>
<?php endif ?>
<?php echo $this->getChildHtml('catalog.leftnav');?>
<?php echo $this->getChildHtml('filter_catalog');?>
