<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/5/17
 * Time: 5:42 PM
 */
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head"><?php echo $this->__('Block IP classes or single IP'); ?></h3></td>
            <td class="form-buttons">
                <button title="<?php echo $this->__('View list'); ?>" type="button" class="scalable " onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('*/*/index'); ?>')" style="">
                    <span><span><span><?php echo $this->__('View list'); ?></span></span></span>
                </button>
                <button title="<?php echo $this->__('View blocked'); ?>" type="button" class="scalable " onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('*/*/blocked'); ?>')" style="">
                    <span><span><span><?php echo $this->__('View blocked'); ?></span></span></span>
                </button>
                <button title="<?php echo $this->__('View white list'); ?>" type="button" class="scalable " onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('*/*/white'); ?>')" style="">
                    <span><span><span><?php echo $this->__('View white list'); ?></span></span></span>
                </button>
                <button title="<?php echo $this->__('View watch list'); ?>" type="button" class="scalable " onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('*/*/watch'); ?>')" style="">
                    <span><span><span><?php echo $this->__('View watch list'); ?></span></span></span>
                </button>
                <button title="<?php echo $this->__('Block ip classes'); ?>" type="button" class="scalable " onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('*/*/oneip'); ?>')" style="">
                    <span><span><span><?php echo $this->__('Block ip classes'); ?></span></span></span>
                </button>
            </td>
        </tr>
    </table>
</div>
<div>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo $this->__('You can use * as a wildcard to block an entire IP class. Ex: 192.168.0.*'); ?>
                </li>
            </ul>
        </li>
    </ul>
</div>
<br />
<div class="grid" style="width: 500px;">
    <table class="data" cellspacing="0">
        <thead>
        <tr class="headings">
            <th colspan="2" style="padding: 5px;">
                <?php echo $this->__('Block this ip'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <tr class="even">
            <td style="padding: 15px;" width="60%">
                <input type="text" class="input-text" id="ip_to_block" value="" style="width: 220px;" />
            </td>
            <td style="padding: 15px; text-align: center;">
                <button title="<?php echo $this->__('Block this ip'); ?>" type="button" class="scalable " onclick="block_one_ip();" style="">
                    <span><span><span><?php echo $this->__('Block this ip'); ?></span></span></span>
                </button>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<br />

<div class="grid" style="width: 500px;">
    <table class="data" cellspacing="0" id="blocked_ip_classes">
        <thead>
        <tr class="headings">
            <th colspan="2" style="padding: 5px;">
                <?php echo $this->__('Blocked ip classes'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php

        $arrBlocked = Mage::helper('visitoripsecurity')->getBlocked();
        $i = 0;
        foreach ($arrBlocked as $k => $v){
            if(stripos($v, "*") !== false){
                $i++;
                ?>
                <tr class="even">
                    <td style="padding: 5px;" width="60%"><?php echo $v; ?></td>
                    <td style="padding: 5px; text-align: center;">
                        <button title="<?php echo $this->__('Unblock this ip'); ?>" type="button" class="scalable " onclick="unblock_one_ip('<?php echo $v; ?>', this);" style="">
                            <span><span><span><?php echo $this->__('Unblock this ip'); ?></span></span></span>
                        </button>
                    </td>
                </tr>

                <?php
            }
        }

        //var_dump($arrBlocked);
        ?>
        </tbody>
    </table>
</div>
<?php
$button = '<button title="'.$this->__('Unblock this ip').'" type="button" class="scalable " onclick="unblock_one_ip('.$v.', this);" style="">';
$button .= '<span><span><span>'.$this->__('Unblock this ip').'</span></span></span>';
$button .= '</button>';
?>
<script type="text/javascript">
    function block_one_ip(){
        var ip_to_bl = document.getElementById('ip_to_block').value;
        if(ip_to_bl){
            //alert(ip_to_bl);
            new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/blockOneIp") ?>', {
                method: 'post',
                parameters: { ip: ip_to_bl},
                onSuccess: function(response){
                    //alert(response.responseText);
                    if(response.responseText == 'blocked'){
                        $('messages').update('<ul class="messages"><li class="notice-msg"><ul><li><?php echo $this->__('IP'); ?> '+ip_to_bl+' <?php echo $this->__('was blocked'); ?></li></ul></li></ul>');
                        //$('blocked_ip_classes').insert('<tr class="even"><td style="padding: 5px;">'+ip_to_bl+'</td><td style="padding: 5px; text-align: center;"></td></tr>');
                        tr = new Element('tr').addClassName('even');
                        tr.insert(new Element('td').setStyle({'padding': '5px'}).update(ip_to_bl));
                        tr.insert(new Element('td').setStyle({'textAlign': 'center', 'padding': '5px'}).update(''));
                        $('blocked_ip_classes').down('tbody').insert(tr);
                    }else{
                        $('messages').update('<ul class="messages"><li class="notice-msg"><ul><li>'+response.responseText+'</li></ul></li></ul>');
                    }

                    //$(button).up().update(response.responseText);

                }
            });
        }else{
            alert('<?php echo $this->__('Ip field cannot be empty!'); ?>');
        }
    }
    function unblock_one_ip(ip, field){

        //alert(ip_to_bl);
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/unblockOneIp") ?>', {
            method: 'post',
            parameters: { ip: ip},
            onSuccess: function(response){
                //alert(response.responseText);
                $('messages').update('<ul class="messages"><li class="notice-msg"><ul><li>'+response.responseText+'</li></ul></li></ul>');
                $(field).up(1).hide();
                //$(button).up().update(response.responseText);

            }
        });

    }

</script>

<?php
?>
