<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/30/16
 * Time: 5:10 PM
 */

$_helper    = $this->helper('catalog/output');
?>
<?php $_topCategories = $this->getCurrentChildCategories();?>
<?php if($_topCategories->count()): ?>
    <ul class="ul-outside display-inline margin-top-md">
    <?php $i = true; foreach ($_topCategories as $_childCategory): ?>
        <?php if($_childCategory->getIsActive()): ?>
            <?php $_category = Mage::getModel('catalog/category')->load($_childCategory->getId()); ?>
                <li><a href="<?php echo $_category->getUrl()?>"><?php echo $this->htmlEscape($_category->getName()) ?></a> (<?php echo $_category->getProductCount()?>)</li>
        <?php endif;?>
    <?php endforeach;?>
    </ul>
<?php endif; ?>