<?php
/**
 * Created by PhpStorm.
 * User: nick
 * Date: 12/2/16
 * Time: 8:35 PM
 */

// add static block  {{block type="catalog/navigation" template="catalog/navigation/subcategory_listing.phtml"}}
//   System->Permissions->Blocks and add your block catalog/navigation in that list.

$helper = Mage::helper('catalog/category');
$category = Mage::getModel('catalog/category');
?>
<div class="portlet light portlet-fit bordered">
    <div class="portlet-body form">
        <div class="panel-group accordion" id="accordion3">
            <?php $_categories = $this->getCurrentChildCategories();?>
            <?php if($_categories->count()): ?>
                <?php $i = true; foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive()): ?>
                        <div class="panel panel-list">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse" data-parent="#accordion3" href="#collapse_3_<?php echo $_category->getId()?>"> <?php echo $this->htmlEscape($_category->getName()) ?> </a>
                                </h4>
                            </div>
                            <div id="collapse_3_<?php echo $_category->getId()?>" class="panel-collapse <?php echo $i ? 'in' : 'collapse'; ?>">
                                <?php $childrenCategoryIds = explode(',', $_category->getChildren()); ?>
                                <div class="panel-body">
                                    <!-- Show Catalog image-->
                                    <div class="img-catalog">
                                        <img class="img-responsive"  src="<?php echo $_category->getImageUrl()?>" alt="">
                                    </div>
                                    <p class="text-transform"><a href="<?php echo $_category->getUrl()?>"> <?php echo $this->htmlEscape($_category->getName()); ?></a> (<?php echo $_category->getProductCount()?>):</p>
                                    <ul class="ul-outside display-inline">
                                        <?php foreach($childrenCategoryIds as $_childId): ?>
                                            <?php $childCategory = $category->load($_childId); ?>
                                            <?php if($childCategory->getIsActive()): ?>
                                                <li><a href="<?php echo $childCategory->getUrlPath()?>"><?php echo $this->htmlEscape($childCategory->getName()) ?></a></li>
                                            <?php endif ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                     <?php endif; ?>
                <?php $i = false; endforeach; ?>
            <?php endif; ?>
         </div>
    </div>
</div>
