<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/23/17
 * Time: 11:21 AM
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function editConfigurationField(fieldId)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/editParserSetting') ?>', {
            method: 'post',
            parameters: { id: fieldId},
            onSuccess: function(response) {
                if (200 == response.status){
                    win = new Window({
                        className: 'magento',
                        title: '<?php echo Mage::helper('company')->__("Parser Setting")?>',
                        width:550,
                        height:650,
                        destroyOnClose: true,
                        recenterAuto:false
                    });
                    win.getContent().update(response.responseText);
                    win.showCenter();
                }
            }
        });
    }
    function saveParserSetting(editor)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/saveParserSetting') ?>', {
            method: 'post',
            parameters: { settings: JSON.stringify(editor.getValue()) },
            onSuccess: function(response){
                if(200 == response.status){
                    editor.destroy();
                    win.close();
                }
            }
        });
    }
    //]]>
</script>
