<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/23/17
 * Time: 4:01 PM
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function editPriceType()
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/editPriceType') ?>', {
            method: 'post',
            parameters: { id: '<?php echo Mage::registry('current_company')->getId()?>'},
            onSuccess: function(response) {
                if (200 == response.status){
                    win = new Window({
                        className: 'magento',
                        title: '<?php echo Mage::helper('company')->__("Price Type Editor")?>',
                        width:800,
                        height:500,
                        destroyOnClose: true,
                        recenterAuto:false
                    });
                    win.getContent().update(response.responseText);
                    win.showCenter();
                }
            }
        });
    }
    function addPriceType()
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/addPriceType') ?>', {
            method: 'post',
            parameters: { id: '<?php echo Mage::registry('current_company')->getId()?>'},
            onSuccess: function(response) {
                if (200 == response.status){
                    win = new Window({
                        className: 'magento',
                        title: '<?php echo Mage::helper('company')->__("Price New Type")?>',
                        width:550,
                        height:400,
                        destroyOnClose: true,
                        recenterAuto:false
                    });
                    win.getContent().update(response.responseText);
                    win.showCenter();
                }
            }
        });
    }
    function savePriceType(button, fieldId)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/updateConfiguration') ?>', {
            method: 'post',
            parameters: { id: fieldId, settings: editor.getValue() }
        });
    }
    //]]>
</script>
