<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/28/17
 * Time: 11:49 AM
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function newConfiguration(fieldId)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/newConfigurationPopup') ?>', {
            method: 'post',
            parameters: { id: fieldId},
            onSuccess: function(response) {
                if (200 == response.status){
                    win = new Window({
                        className: 'magento',
                        title: '<?php echo Mage::helper('company')->__("New Configuration")?>',
                        width:650,
                        height:500,
                        destroyOnClose: true,
                        recenterAuto:false
                    });
                    win.getContent().update(response.responseText);
                    win.showCenter();
                }
            }
        });
    }
    function saveNewConfiguration(button, fieldId)
    {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/parser_parser/saveNewConfiguration') ?>', {
            method: 'post',
            parameters: { id: fieldId, settings: editor.getValue() }
        });
    }
    //]]>
</script>
