<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 10/2/17
 * Time: 11:23 AM
 */
?>

<script type="text/javascript">
    "type": {
        title: "<?php echo Mage::helper('company')->__('Source Type'); ?>",
            "type": "string",
            "enum": ["xls", "csv", "xml"],
            "default": "<?php echo $settings['type']?>",
            "description": "Select File Type"
    },
</script>
