<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/11/16
 * Time: 12:28 PM
 */
?>

<div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                <h4 class="modal-title text-center">Написать нам</h4>
            </div>
            <div class="modal-body modal-body-form">
                <div class="form-group">
                    <label class="control-label">Ваше имя:</label>
                    <input type="text" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label">Номер телефона:</label>
                    <input type="text" placeholder="+38 ( _ _ _ ) _ _ - _ _ - _ _" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label">E-mail:<span class="has-span">*</span> </label>
                    <input type="text" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label">Сообщение:<span class="has-span">*</span> </label>
                    <textarea rows="3" class="form-control radius-none"></textarea>
                </div>
                <div class="form-group">
                    <p class="txt-sm">
                        Поля, обозначенные <span class="has-span">*</span> обязательны для заполнения
                    </p>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn yellow btn-lg btn-width border-radius-none bold margin-top-min">Отправить</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
