<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/11/16
 * Time: 12:28 PM
 */
?>

<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/stableflow/default/quick_contact/js/quickContact.js'?>" type="text/javascript"></script>
<style>
    .ajax-contact-overlay{
        display: none;
        position: fixed;
        width: 100%;
        height: 100%;
        opacity: 0.5;
        background-color: #363636;
        z-index: 10000;
        top: 0;
        left: 0;
    }
    .ajax-contact-loader{
        display: none;
        width: 60px;
        height: 60px;
        position: fixed;
        left: 50%;
        top: 50%;
        z-index: 1000000;
        transform: translate3d(-50%,-50%,0)
    }
</style>
<div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                <h4 class="modal-title text-center"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h4>
            </div>
            <form action="<?php echo Mage::getBaseUrl(); ?>quickcontact/index/post" id="contactForm" method="post" class="scaffold-form">
                <div class="modal-body modal-body-form">
                    <div class="form-group" style="display: none">
                        <label class="control-label"><?php echo Mage::helper('contacts')->__('Product Name') ?><span class="has-span">*</span></label>
                        <input name="product_name" id="product_name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Product Name')) ?>" value="" class="input-text required-entry form-control radius-none" type="text" readonly/>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo Mage::helper('contacts')->__('Name') ?><span class="has-span">*</span></label>
                        <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry form-control radius-none" type="text" />
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="form-control radius-none input-text" type="tel" />
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo Mage::helper('contacts')->__('Email') ?><span class="has-span">*</span> </label>
                        <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="form-control radius-none input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo Mage::helper('contacts')->__('Comment') ?><span class="has-span">*</span> </label>
                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="form-control radius-none required-entry input-text" cols="5" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <p class="txt-sm">
                            <?php echo Mage::helper('contacts')->__('* Required Fields') ?>
                        </p>
                    </div>
                    <?php echo $this->getChildHtml('recaptcha'); ?>
                    <div class="form-group text-center">
                        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                        <button id="submit" type="submit" class="btn yellow btn-lg btn-width border-radius-none bold margin-top-min"><?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?></button>
                    </div>
                    <div id="loader"></div>
                </div>
            </form>
            <?php $imgSrc = $this->getSkinUrl('images/company/rolling.svg'); ?>
            <div class="ajax-contact-overlay"></div>
            <div class="ajax-contact-loader">
                <img width="60" height="60" src="<?php echo $imgSrc ?>" />
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    jQuery('#draggable').on('show.bs.modal', function(e) {

        //get data-id attribute of the clicked element
        var productName = jQuery(e.relatedTarget).data('product-name');
        var productNameBlock = jQuery(e.currentTarget).find('input[name="product_name"]');
        if(productName) {
            productNameBlock.prop('enabled', true);
            productNameBlock.val(productName);
            productNameBlock.parent(".form-group").css("display", "block");
        }else{
            productNameBlock.parent(".form-group").css("display", "none");
            productNameBlock.prop('disabled', true);
        }
    });
    //]]>
</script>