<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/11/16
 * Time: 12:27 PM
 */
?>

<?php $helper = Mage::helper('customer');?>

<div class="modal fade draggable-modal" id="login" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form id="login-form-ajax" action="<?php echo $this->getPostActionUrl() ?>" method="post">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    <h4 class="modal-title text-center"><?php echo $this->__('Login') ?></h4>
                </div>
                <div class="modal-body register-form-messages">
                    <?php echo $this->getMessagesBlock()->toHtml() ?>
                    <?php echo $this->getChildHtml('customer.form.register.extra')?>
                </div>
                <div class="modal-body modal-body-form">
                    <div class="form-group">
                        <label class="control-label required" aria-required="true"><?php echo $this->__('Email Address') ?><span class="has-span">*</span> </label>
                        <input name="email" type="text" class="form-control radius-none required-entry validate-email" aria-describedby="email-error" aria-invalid="true" aria-required="true">
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo $this->__('Password') ?></label>
                        <input name="password" type="password" class="form-control radius-none required-entry validate-password">
                    </div>
                    <div class="form-group">
                        <p class="txt-sm"><?php echo $this->__('* Required Fields') ?></p>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn yellow margin-top-min min-width"><?php echo $this->__('Login') ?></button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form-ajax', true);
    ajaxlogin.init();
    //]]>
</script>