<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/11/16
 * Time: 12:27 PM
 */
?>

<div class="modal fade draggable-modal" id="login" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                <h4 class="modal-title text-center">вход</h4>
            </div>
            <div class="modal-body modal-body-form">
                <div class="form-group">
                    <label class="control-label required" aria-required="true">E-mail:<span class="has-span">*</span> </label>
                    <input name="email" type="text" class="form-control radius-none" aria-describedby="email-error" aria-invalid="true" aria-required="true">
                </div>
                <div class="form-group">
                    <label class="control-label">Пароль:</label>
                    <input name="password" type="password" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <p class="txt-sm">
                        Поля, обозначенные <span class="has-span">*</span> обязательны для заполнения
                    </p>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn yellow margin-top-min min-width">Вход</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
