<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/11/16
 * Time: 12:28 PM
 */
?>
<?php // Register window ?>
<div class="modal fade draggable-modal" id="user_registration" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                <h4 class="modal-title text-center"><?php echo $this->__('Registration') ?></h4>
            </div>
            <div class="modal-body modal-body-form">
                <div class="form-group">
                    <label class="control-label"><?php echo $this->__('First Name') ?><span class="has-span">*</span> </label>
                    <input type="text" name="firstname" placeholder="<?php echo $this->__('First Name') ?>" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label">Номер телефона:</label>
                    <input type="text" name="telephone" placeholder="+38 ( _ _ _ ) _ _ - _ _ - _ _" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label"><?php echo $this->__('E-mail address') ?><span class="has-span">*</span> </label>
                    <input type="text" name="email" class="form-control radius-none">
                </div>
                <div class="form-group">
                    <label class="control-label"><?php echo $this->__('Password') ?><span class="has-span">*</span></label>
                    <input type="password" name="password" class="form-control radius-none required-entry validate-password">
                </div>
                <div class="form-group">
                    <label class="control-label"><?php echo $this->__('Password confirmation') ?><span class="has-span">*</span></label>
                    <input type="password" name="passwordConfirm" class="form-control radius-none required-entry validate-cpassword">
                </div>
                <div class="form-group">
                    <p class="txt-sm"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="form-group checkbox-group">
                    <input type="checkbox" name="licence" checked="" id="checkbox2">
                    <label class="checkbox-label" for="checkbox2">
                        <?php echo $this->__('I accept the') ?> <a href="#" target="_blank"><?php echo $this->__('Terms and Coditions') ?></a>
                    </label>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn yellow margin-top-min min-width"> <?php echo $this->__('Register') ?></button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);

    //]]>
</script>