<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 3/1/17
 * Time: 2:15 PM
 */
?>
<?php $_helper = Mage::helper('company');?>
<?php $company = Mage::registry('current_company')?>
<?php $address = Mage::getModel('company/address')->load($company->getAddressId());?>
<?php if($address->getData('country_id')) :?>
    <p><span class="bold"><?php echo $this->__('Country:')?> </span><?php echo Mage::getModel('directory/country')->loadByCode($address->getData('country_id'))->getName();?></p>
<?php endif; ?>
<p><span class="bold"><?php echo $this->__('Address:')?> </span><?php echo $address->getData('city');?> <?php echo $address->getData('street');?> </p>
<p><span class="bold"><?php echo $this->__('Telephone:')?> </span>
    <span class="left-content">
       <?php echo $address->getData('telephone');?>
    </span>
</p>
<p><span class="bold"><?php echo $this->__('Email:')?> </span><a class="link-underline" href="<?php echo $address->getEmail(); ?>"><?php echo $address->getEmail(); ?></a></p>
<p><span class="bold"><?php echo $this->__('Site:')?> </span><a class="link-underline" href="<?php echo $company->getUrl(); ?>"><?php echo $_helper->formatUrl($company->getUrl()); ?></a></p>

<div class="content-text content-description-outside">
    <?php echo $company->getDescription()?>
</div>
