<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 2/6/17
 * Time: 12:50 PM
 */

?>
<?php $manuals = $this->getManual();?>
<?php if(count($manuals)): ?>
    <ul class="line-pdf">
    <?php foreach($manuals as $manual): ?>
        <li><a href="<?php echo $this->htmlEscape($manual['file']);?>"><img src="<?php  echo $this->getSkinUrl('images/user_manual/img-pdf.png')?>"></a></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
