<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/18/16
 * Time: 4:37 PM
 */

$id = $this->getRecaptchaId();
?>
<?php if ($this->isAllowed($this->getAction()->getFullActionName())): ?>

<div class="recaptcha" style="overflow:hidden;position:relative;margin-bottom:10px;">
    <input type="checkbox" id="cb-<?php echo $id ?>" name="cb-<?php echo $id ?>" value="" class="hide required-entry" style="visibility:hidden; position:absolute; left:-1000000px" />
    <div id="el-<?php echo $id ?>" class="g-recaptcha" data-sitekey="<?php echo $id ?>"></div>
</div>
<?php endif; ?>