<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/17/16
 * Time: 4:23 PM
 */
?>
<script type="text/javascript">
    var CaptchaCallback = function(){
        jQuery('.g-recaptcha').each(function(index, el) {
            grecaptcha.render(el, {
                'sitekey': "<?php echo $this->getSiteKey(); ?>",
                'theme': "<?php echo $this->getTheme(); ?>",
                'type': "<?php echo $this->getType(); ?>",
                'size': "<?php echo $this->getSize(); ?>",
                'callback': function(response) {
                    if (response.length > 0) {
                        var key = jQuery(el).data('sitekey');
                        $('cb-' + key).writeAttribute('value', 'checked');
                        $('cb-' + key).checked = true;
                    }
                }
            });
        });
    };
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=CaptchaCallback&render=explicit" async defer></script>

