<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 1/17/17
 * Time: 5:03 PM
 */

$text = '<ul class="ul-outside">';
$childrenCategoryIds = explode(',', $_category->getChildren());
foreach($childrenCategoryIds as $_childId) {
    $childCategory = Mage::getModel('catalog/category')->load($_childId);
    if ($childCategory->getIsActive()) {
        $text .= '<li><a href="' . $childCategory->getUrlPath() . '">' . $this->htmlEscape($childCategory->getName()) . '</a></li>';
    }
    if($childCategory->hasChildren()){
        $text .= '<li class="list-unstyled">' . $this->getRecursionChild($childCategory) . '</li>';
    }
}
$text .= '</ul>';
return $text;