<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 12/20/16
 * Time: 5:10 PM
 */
?>

<?php $company = $this->getCompany()?>
<?php $_helper = Mage::helper('company');?>
<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body ">
        <div class="timeline timeline-lg">
            <!-- TIMELINE ITEM -->
            <div class="timeline-badge">
                <a href="<?php echo $company->getUrl();?>" target="_blank" class="company-link">
                    <img class="timeline-badge-userpic" src="<?php echo $_helper->getImageUrl($company);?>">
                </a>
                <a href="<?php echo $company->getUrl();?>" class="link-md link-underline" target="_blank"><?php echo $_helper->formatUrl($company->getUrl());?></a>
            </div>
            <div class="timeline-body clearfix">
                <div class="timeline-body-head">
                    <div class="timeline-body-head-caption">
                        <span class="timeline-body-title font-blue-madison"><?php echo $company->getName();?></span>
                    </div>
                </div>
                <?php echo $this->getChildHtml('company_rating'); ?>
                <div class="timeline-body-content">
                    <?php echo $this->getChildHtml('company_address'); ?>
                </div>
            </div>
            <!-- END TIMELINE ITEM -->
        </div>

        <!-- Tabs content -->
        <div class="tabbable tabbable-tabdrop">
            <div id="tabs">
                <ul class="nav nav-tabs">
                    <?php $i = 1; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $groupTab => $html):?>
                        <li>
                            <?php
                            if ($title = $this->getChildData($groupTab, 'title'));
                            else
                                $title = $groupTab;
                            ?>
                            <a href="#tabs-<?php echo $i;?>"><?php echo $this->escapeHtml($title); ?></a>
                            <?php $html_render .= '<div id="tabs-'. $i . '">' .  $html . '</div>'; $i++;?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="tab-content">
                    <?php echo $html_render; ?>
                </div>
            </div>
            <script  type="text/javascript">
                //<![CDATA[
                jQuery(document).ready(function(){
                    jQuery( "#tabs" ).tabs();
                });
                //]]>
            </script>
        </div>
        <!-- END Tabs content -->



    </div>
</div>
