<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/9/16
 * Time: 5:49 PM
 */

?>

<?php if($this->getCollection()->getSize()): ?>
    <div class="type-content toolbar">
        <div class="pager pager-inline clearfix">
            <p class="amount">
                <?php if($this->getLastPageNum()>1): ?>
                    <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                <?php else: ?>
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                <?php endif; ?>
            </p>
            <?php echo $this->getPagerHtml() ?>
            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </div>
        </div>

    </div>
<?php endif ?>