<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 12/15/16
 * Time: 6:23 PM
 */
?>
<div class="stars-rating">
    <?php foreach ($this->_votes as $_vote): ?>
            <?php //echo $this->escapeHtml($_vote->getRatingCode()) ?>
            <?php $rating = $_vote->getPercent() ?>
            <?php $numOfStar = intval($rating * 5 / 100);?>
            <?php for($i = 5; $i != 0; $i--):?>
                <input type="radio" disabled="disabled" <?php echo $numOfStar-- > 0 ?  'checked="checked"' : '' ?> name="star-rating-<?php echo $i;?>">
                <label for="star-rating-<?php echo $i;?>" class="radio-label"></label>
            <?php endfor;?>
    <?php endforeach; ?>
</div>