<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 3/3/17
 * Time: 5:25 PM
 */
?>

<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="comment-content">
    <div class="c-comment-list">
        <!-- Review text content -->
        <?php if (count($_items)) :?>
            <?php foreach ($_items as $_review) :?>
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <span><?php echo $this->escapeHtml($_review->getNickname()); ?></span>
                            <span class="c-date"><?php echo $this->escapeHtml($_review->getCreatedAt()); ?></span>
                        </h4>
                        <?php $_votes = $_review->getRatingVotes(); ?>
                        <!-- Rating stars -->
                        <?php if (count($_votes = $_review->getRatingVotes())) :?>
                            <?php// echo $this->getBlockHtml('company_rating');?>
                            <?php $ratingBlock = $this->getLayout()->getBlock('company_rating');?>
                            <?php $ratingBlock->setData('_votes', $_votes);?>
                            <?php echo $ratingBlock->toHtml();?>
                        <?php endif; ?>
                        <!-- End Rating stars -->
                        <?php echo nl2br($this->escapeHtml($_review->getDetail())); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <!-- End Review text content -->
            <?php else: ?>
            <?php echo Mage::helper('company')->__('There are no reviews at this moment'); ?>
        <?php endif; ?>
    </div>
</div>

