<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/6/16
 * Time: 5:19 PM
 */
?>
<div class="bnt-block clearfix">
    <a class="btn default btn-block btn-outline" href="javascript:;"> Информация для компаний и рекламодателей </a>
    <a class="btn default btn-block btn-outline" href="javascript:;"> Правила и стоимость размещения прайс-листов </a>
    <a class="btn default btn-block btn-outline" href="javascript:;"> Правила и стоимость размещения товаров под заказ   </a>
</div>
<ul class="navs-info">
    <li><a data-toggle="modal" href="#draggable">Написать нам</a></li>
    <li><a href="">Карта сайта</a></li>
</ul>
