<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 3/29/17
 * Time: 5:27 PM
 */

?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    <h4 class="modal-title text-center">редактирование <br />  персональной информации</h4>
                </div>
                <div class="modal-body modal-body-form">
                    <div class="form-group">
                        <label class="control-label">Фамилия:</label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Имя:<span class="has-span">*</span> </label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Отчество: </label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Номер телефона:</label>
                        <input type="text" placeholder="+38 ( _ _ _ ) _ _ - _ _ - _ _" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Область:<span class="has-span">*</span> </label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Город:<span class="has-span">*</span> </label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Адрес: </label>
                        <input type="text" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <p class="txt-sm">
                            Поля, обозначенные <span class="has-span">*</span> обязательны для заполнения
                        </p>
                    </div>
                    <div class="form-group text-center row-position">
                        <a href="" class="clear-editor link-underline">Отмена</a>
                        <button type="button" class="btn yellow btn-lg btn-width border-radius-none bold margin-top-min">сохранить</button>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->

</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>