<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/2/16
 * Time: 4:28 PM
 */
?>

<?php // If user is not logged in ?>
<?php if (Mage::helper('customer')->isLoggedIn() != true) : ?>

    <?php // Login window ?>





    <?php // Youama jQuery plugin for ajax call and windows ?>
    <script type="text/javascript">
        //<![CDATA[
        jQuery(document).ready(function(){
            ajaxlogin.init(
                '<?php echo $this->isRedirectToProfile() ?>',
                '<?php echo Mage::getBaseUrl() ?>customer/account/',
                '<?php echo $autoShowUp = (isset($_GET['yregister'])) ? 'yes' : 'no' ?>',
                '<?php echo $this->getUrl('youama_ajaxlogin/ajax/index') ?>'
            );
        });
        //]]>
    </script>

<?php endif ?>
