<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/2/16
 * Time: 4:28 PM
 */
?>

<?php // If user is not logged in ?>
<?php if (Mage::helper('customer')->isLoggedIn() != true) : ?>

    <?php // Login window ?>
    <div class="modal fade draggable-modal" id="login" tabindex="-1" role="basic" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    <h4 class="modal-title text-center">вход</h4>
                </div>
                <div class="modal-body modal-body-form">
                    <div class="form-group">
                        <label class="control-label required" aria-required="true">E-mail:<span class="has-span">*</span> </label>
                        <input name="email" type="text" class="form-control radius-none" aria-describedby="email-error" aria-invalid="true" aria-required="true">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Пароль:</label>
                        <input name="password" type="password" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <p class="txt-sm">
                            Поля, обозначенные <span class="has-span">*</span> обязательны для заполнения
                        </p>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn yellow margin-top-min min-width">Вход</button>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>


    <?php // Register window ?>
    <div class="modal fade draggable-modal" id="user_registration" tabindex="-1" role="basic" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    <h4 class="modal-title text-center"><?php echo $this->__('Registration') ?></h4>
                </div>
                <div class="modal-body modal-body-form">
                    <div class="form-group">
                        <label class="control-label"><?php echo $this->__('First Name') ?><span class="has-span">*</span> </label>
                        <input type="text" name="firstname" placeholder="<?php echo $this->__('First Name') ?>" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Номер телефона:</label>
                        <input type="text" name="telephone" placeholder="+38 ( _ _ _ ) _ _ - _ _ - _ _" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo $this->__('E-mail address') ?><span class="has-span">*</span> </label>
                        <input type="text" name="email" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo $this->__('Password') ?><span class="has-span">*</span></label>
                        <input type="password" name="password" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?php echo $this->__('Password confirmation') ?><span class="has-span">*</span></label>
                        <input type="password" name="passwordConfirm" class="form-control radius-none">
                    </div>
                    <div class="form-group">
                        <p class="txt-sm">
                            Поля, обозначенные <span class="has-span">*</span> обязательны для заполнения
                        </p>
                    </div>
                    <div class="form-group checkbox-group">
                        <input type="checkbox" name="licence" checked="" id="checkbox2">
                        <label class="checkbox-label" for="checkbox2">
                            <?php echo $this->__('I accept the') ?> <a href="#" target="_blank"><?php echo $this->__('Terms and Coditions') ?></a>
                        </label>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn yellow margin-top-min min-width"> <?php echo $this->__('Register') ?></button>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <?php // Youama jQuery plugin for ajax call and windows ?>
    <script type="text/javascript">
        //<![CDATA[
        jQuery(document).ready(function(){
            ajaxlogin.init(
                '<?php echo $this->isRedirectToProfile() ?>',
                '<?php echo Mage::getBaseUrl() ?>customer/account/',
                '<?php echo $autoShowUp = (isset($_GET['yregister'])) ? 'yes' : 'no' ?>',
                '<?php echo $this->getUrl('youama_ajaxlogin/ajax/index') ?>'
            );
        });
        //]]>
    </script>

<?php endif ?>
