<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 3/9/17
 * Time: 11:31 AM
 */
?>
<div class="stars-rating">
<?php if(!empty($collection) && $collection->getSize()): ?>
        <?php foreach ($collection as $_rating): ?>
            <?php if($_rating->getSummary()): ?>
                <?php //echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?>
                <?php $rating = $_rating->getSummary() ?>
                <?php $numOfStar = intval($rating * 5 / 100);?>
                <?php for($i = 5; $i != 0; $i--):?>
                    <!--<input type="radio" disabled="disabled" <?php /*echo $numOfStar-- > 0 ?  'checked="checked"' : '' */?> name="star-rating-<?php /*echo $i;*/?>">
                    <label for="star-rating-<?php /*echo $i;*/?>" class="radio-label"></label>-->
                <input type="radio" disabled="disabled" <?php echo $numOfStar-- > 0 ?  'checked="checked"' : '' ?> name="">
                <label for="" class="radio-label"></label>
                <?php endfor;?>
            <?php endif; ?>
        <?php endforeach; ?>
<?php endif; ?>
</div>

