<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 8/15/16
 * Time: 5:19 PM
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_posts = $this->getPosts(); ?>
<h3 class="page-title">
    <?php if (Mage::helper('mageplaza_betterblog/post')->isRssEnabled()) : ?>
        <div class="betterblog-rss">
            <a href="<?php echo Mage::helper('mageplaza_betterblog/post')->getRssUrl(); ?>" class="bb-rss-icon"><img
                    src="<?php echo $this->getSkinUrl('images/mageplaza_betterblog/rss.png') ?>" width="16px"/> </a>
        </div>
    <?php else : ?>
        <?php echo $this->__('News / Article');?>
    <?php endif; ?>
</h3>
<?php if ($_posts->getSize() > 0) : ?>
    <?php //echo $this->getPagerHtml(); ?>
    <div class="portlet light portlet-fit bordered">
        <div class="portlet-body">
            <div class="row">
                <div class="col-md-9 col-sm-9 col-news">
                    <div class="row media-list">
                        <?php foreach($_posts as $_post):?>
                            <div class="col-md-6 col-sm-6">
                                <div class="media">
                                    <div class="media-left">
                                        <?php if ($_post->getImage()) : ?>
                                            <a href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $_post->getPostTitle(); ?>">
                                                <img class="media-object"
                                                     src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image')->resize(100); ?>"
                                                     alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>"/>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            <a href="<?php echo $_post->getPostUrl() ?>">
                                                <?php echo $_post->getPostTitle(); ?>
                                            </a>
                                            <span class="media-date"><?php echo $_post->getDate('created_at')?></span>
                                        </h4>
                                        <?php echo $_post->getPostExcerpt(); ?><?php echo $this->__('[...]'); ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <?php //echo $this->getPagerHtml(); ?>
<?php else : ?>
    <div class="post-list-container">
        <?php echo Mage::helper('mageplaza_betterblog')->__('There are no posts at this moment'); ?>
    </div>
<?php endif; ?>

