<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:59 PM
 */
?>
<?php $productId = Mage::registry('current_product')->getId();?>

<?php $companyIds = Mage::getModel('company/relation')->getCollection()->addFieldToFilter('product_id', $productId);?>

<div class="table-responsive">
    <table class="table table-bordered table-middle table-padding">
        <thead>
        <tr>
            <th><?php echo $this->__('Supplier')?></th>
            <th><?php echo $this->__('Price')?></th>
            <th><?php echo $this->__('Rating')?></th>
            <th><?php echo $this->__('Availability')?></th>
            <th><?php echo $this->__('Topicality')?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($companyIds as $_company):?>
            <?php //print_r($company)?>
            <?php $company = Mage::getModel('company/company')->load($_company->getCompanyId()); ?>
            <?php $product = Mage::getModel('company/product')->load((int)$_company->getCompanyProductId()); ?>
            <tr>
                <td><a href="<?php echo $company->getCompanyUrl(); ?>"> <?php echo $company->getName(); ?></a></td>
                <td><?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?></td>
                <td>
                    <?php echo $this->getChildHtml('rating'); ?>
                </td>
                <td><?php echo $product->getQty() ? '+' : '-'; ?></td>
                <td>
                    <?php echo $this->getChildHtml('topicality'); ?>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>

