<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:59 PM
 */
?>
<?php $productId = Mage::registry('current_product')->getId();?>
<?php $offers = $this->getOffers($productId)?>


<div class="table-responsive">
    <table class="table table-bordered table-middle table-padding">
        <thead>
        <tr>
            <th><?php echo $this->__('Supplier')?></th>
            <th><?php echo $this->__('Price')?></th>
            <th><?php echo $this->__('Rating')?></th>
            <th><?php echo $this->__('Availability')?></th>
            <th><?php echo $this->__('Topicality')?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($offers as $_offers):?>
            <tr>
                <td><a href="<?php echo $_offers->getUrl(); ?>"> <?php echo $_offers->getName(); ?></a></td>
                <td><?php echo $_offers->getFormatPrice(); ?></td>
                <td>
                    <?php //echo $this->getChildHtml('rating'); ?>
                    <div class="stars-rating">
                        <!--<style>
                            .stars-rating .radio-label::before {
                                color: #525252;
                            }
                        </style>-->
                        <?php for($i = 5; $i != 0; $i--): ?>
                            <input type="radio" disabled="disabled" name="star-rating-<?php echo $i?>">
                            <label  for="star-rating-<?php echo $i?>" class="radio-label"></label>
                        <?php endfor ;?>
                    </div>
                </td>
                <td><?php echo ($_offers->getAvailable() > 0) ? '+' : '-'; ?></td>
                <td>
                    <?php //echo $this->getChildHtml('topicality'); ?>
                    <div class="stars-rating">
                        <!--<style>
                            .stars-rating .radio-label::before {
                                color: #525252;
                            }
                        </style>-->
                        <?php for($i = 5; $i != 0; $i--): ?>
                            <input type="radio" disabled="disabled" name="star-rating-<?php echo $i?>">
                            <label  for="star-rating-<?php echo $i?>" class="radio-label"></label>
                        <?php endfor ;?>
                    </div>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>

