<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/13/16
 * Time: 12:23 PM
 */

$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<div class="label-product clearfix">
    <?php if ($_product->getData('news_from_date')): ?>
       <!-- <span type="button" class="label-span label-yellow"><?php echo $this->__('New');?></span>-->
    <?php endif; ?>
    <?php if ($_product->getData('sale')): ?>
        <span type="button" class="label-span label-primary"><?php echo $this->__('Sale');?></span>
    <?php endif; ?>
    <?php if ($_product->getData('promo')): ?>
        <span type="button" class="label-span label-yellow-light"><?php echo $this->__('Promo');?></span>
    <?php endif; ?>
    <?php if ($_product->getData('out_of_production')|| true ): ?>
<!--        <span type="button" class="label-span label-grey">--><?php //echo $this->__('Out of production');?><!--</span>-->
        <?php var_dump($_product);  ?>
        <span type="button" class="label-span label-grey"><?php echo $_product->getData('out_of_production') + "" ;?></span>
    <?php endif; ?>
</div>
