<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 1/23/17
 * Time: 5:59 PM
 */
?>
<?php if($crumbs && is_array($crumbs)): ?>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <?php foreach($crumbs as $_crumbName => $_crumbInfo): ?>
                <li class="<?php echo $_crumbName ?>">
                    <?php if(isset($_crumbInfo['link']) && !is_null($_crumbInfo['link'])): ?>
                        <a href="<?php echo $_crumbInfo['link'] ?>" <?php if (isset($_crumbInfo['title'])): ?>title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"<?php endif; ?>><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                    <?php elseif($_crumbInfo['last']): ?>
                        <span><?php echo $this->escapeHtml($_crumbInfo['label']) ?></span>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                    <?php endif; ?>
                    <?php if(isset($_crumbInfo['last']) && !$_crumbInfo['last']): ?>
                        <!--span>/ </span-->
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
