<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 5/26/17
 * Time: 1:44 PM
 */
?>
<div id="old" style="display: none;">
    <div id="header">
        <h1>Для просмотра сайта Rulletka используйте, пожалуйста, версии браузера 10,11</h1>
    </div>
    <ul id="modern-browser">
        <hr class="delim" />
        <li class="ie8">
            <h2>Новый Internet Explorer</h2>
            <div class="descriptiontext">
                Современная версия браузера от компании Microsoft. Бесплатно предоставляется всем желающим и свободен для распространения. Если слова «браузер» и «Internet Explorer» для вас не знакомы, установите эту программу.
                <ul class="file">
                    <li class="microsoft" style="padding-left: 0px;"><a href="http://www.microsoft.com/rus/windows/internet-explorer/">Перейти к загрузке Internet Explorer</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>
