<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- Contact menu -->
        <div class="contact-menu text-center underline">
            <span class="phone-number"><i class="icon icon-phone-auricular-and-clock-delivery-symbol"></i><span class="min-sidebar"><?php echo Mage::getStoreConfig('general/store_information/phone');?></span></span>
            <div data-toggle="modal" href="#draggable" class="btn yellow-mint btn-outline min-sidebar"><?php echo $this->__('Ask question')?></div>
            <?php echo $this->getChildHtml('mini.cart'); ?>
        </div>
        <!-- End contact menu -->
        <?php echo $this->getChildHtml('top.menu'); ?>
        <div class="contact-panel">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_panel_left_menu')->toHtml(); ?>
        </div>
        <div class="bnt-block clearfix">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('left_menu_links')->toHtml(); ?>
        </div>
        <?php echo $this->getChildHtml('menu_links');?>
        <!-- END SIDEBAR MENU -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner">
                <div class="max-footer">
                    <address class="copyright"><?php echo Mage::getStoreConfig('design/footer/copyright'); ?></address>
                </div>
            </div>
        </div>
        <!-- END FOOTER -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->


