<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/26/16
 * Time: 1:14 PM
 */
?>
<ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-closed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
    <li class="nav-item  ">
        <a href="javascript:;" class="nav-link nav-toggle underline">
            <i class="icon icon-business"></i>
            <span class="title">Товары</span>
                    <span class="arrow">
                        <i class="icon icon-arrow-point-to-right"></i>
                        <i class="icon icon-arrow-point-down"></i>
                    </span>
        </a>
        <ul class="sub-menu">
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Освещение</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Плитка и сантехника</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Материалы</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Безопасность</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Инструменты и оборудование</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Замки и защелки</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Декор</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-item  ">
        <a href="javascript:;" class="nav-link nav-toggle underline">
            <i class="icon icon-excavator"></i>
            <span class="title">Услуги</span>
                    <span class="arrow">
                        <i class="icon icon-arrow-point-to-right"></i>
                        <i class="icon icon-arrow-point-down"></i>
                    </span>
        </a>
        <ul class="sub-menu">
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Освещение</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Плитка и сантехника</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Материалы</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Безопасность</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Инструменты и оборудование</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Замки и защелки</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <span class="title">Декор</span>
                            <span class="arrow">
                                <i class="icon icon-arrow-point-to-right"></i>
                                <i class="icon icon-arrow-point-down"></i>
                            </span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Плитка</span>
                        </a>
                    </li>
                    <li class="nav-item  ">
                        <a href="" class="nav-link ">
                            <span class="title">Сантехника</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-item">
        <a href="javascript:;" class="nav-link underline">
            <i class="icon icon-newspaper"></i>
            <span class="title">статьи</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="javascript:;" class="nav-link underline">
            <i class="icon icon-interface"></i>
            <span class="title">новости</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="companies.html" class="nav-link underline">
            <i class="icon icon-suitcase"></i>
            <span class="title">компании</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="javascript:;" class="nav-link underline">
            <i class="icon icon-command"></i>
            <span class="title">о нас</span>
        </a>
    </li>

</ul>
