<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 4:29 PM
 */
?>
<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="comment-content">
    <div class="c-comment-list">
        <!-- Review text content -->
        <?php if (count($_items)):?>
            <?php foreach ($_items as $_review):?>
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="#"><?php echo $this->escapeHtml($_review->getNickname())?></a>
                            <span class="c-date">08.04.2016 12:16</span>
                        </h4>
                        <?php $_votes = $_review->getRatingVotes(); ?>
                        <!-- Rating stars -->
                        <?php if (count($_votes)): ?>
                        <div class="stars-rating stars-sm">
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-5">
                            <label for="star-rating-11-5" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-4">
                            <label for="star-rating-11-4" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-3">
                            <label for="star-rating-11-3" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-2">
                            <label for="star-rating-11-2" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-1">
                            <label for="star-rating-11-1" class="radio-label"></label>
                        </div>
                        <?php endif;?>
                        <!-- End Rating stars -->
                        <?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>
                    </div>
                </div>
            <?endforeach;?>
        <?php endif;?>
        <!-- End Review text content -->
    </div>
</div>
<div class="row row-margin">
    <div class="col-md-12">
        <div class="form-group">
            <a class="btn btn-sm yellow btn-width" href="catalog.html">
                <i class="icon icon-arrows_left left-pull"></i>
                вернуться в каталог
            </a>
        </div>
    </div>
</div>
