<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:16 PM
 */?>

<div class="panel-group-tab accordion" id="accordion3">
    <div class="panel panel-list">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse" data-parent="#accordion3" href="#collapse_3_1"> добавить свой отзыв </a>
            </h4>
        </div>
        <div id="collapse_3_1" class="panel-collapse in">
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-label control-label">Ваше имя:<span class="has-span">*</span></label>
                    <div class="col-form">
                        <input type="text" class="form-control radius-none">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label control-label">E-mail:</label>
                    <div class="col-form">
                        <input type="text" class="form-control radius-none">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label control-label">Оценка:</label>
                    <div class="col-form">
                        <div class="stars-rating">
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-1-5">
                            <label for="star-rating-1-5" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-1-4">
                            <label for="star-rating-1-4" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-1-3">
                            <label for="star-rating-1-3" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-1-2">
                            <label for="star-rating-1-2" class="radio-label"></label>
                            <input type="radio" disabled="disabled" checked="checked" name="star-rating-1-1">
                            <label for="star-rating-1-1" class="radio-label"></label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label control-label">Плюсы:</label>
                    <div class="col-form">
                        <div class="panel-ul">
                            <ol>
                                <li>Ярко свети</li>
                                <li>Мало тянет</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label control-label">Минусы:</label>
                    <div class="col-form">
                        <div class="panel-ul">
                            Дорого стоит
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label control-label">Комментарий:</label>
                    <div class="col-form">
                        <textarea class="form-control radius-none" rows="3"></textarea>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="comment-content">
    <div class="c-comment-list">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="#">Анатолий,</a>
                    <span class="c-date">08.04.2016 12:16</span>
                </h4>
                <div class="stars-rating stars-sm">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-5">
                    <label for="star-rating-11-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-4">
                    <label for="star-rating-11-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-3">
                    <label for="star-rating-11-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-2">
                    <label for="star-rating-11-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-1">
                    <label for="star-rating-11-1" class="radio-label"></label>
                </div>
                Купили недавно такие на Вашем сайте, нужно было в качестве студийного света. Очень довольны, светит хорошо, свет белый, все как надо </div>
        </div>
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="#">Анатолий,</a>
                    <span class="c-date">08.04.2016 12:16</span>
                </h4>
                <div class="stars-rating stars-sm">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-12-5">
                    <label for="star-rating-12-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-12-4">
                    <label for="star-rating-12-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-12-3">
                    <label for="star-rating-12-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-12-2">
                    <label for="star-rating-12-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-12-1">
                    <label for="star-rating-12-1" class="radio-label"></label>
                </div>
                Купили недавно такие на Вашем сайте, нужно было в качестве студийного света. Очень довольны, светит хорошо, свет белый, все как надо </div>
        </div>
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="#">Анатолий,</a>
                    <span class="c-date">08.04.2016 12:16</span>
                </h4>
                <div class="stars-rating stars-sm">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-13-5">
                    <label for="star-rating-13-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-13-4">
                    <label for="star-rating-13-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-13-3">
                    <label for="star-rating-13-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-13-2">
                    <label for="star-rating-13-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-13-1">
                    <label for="star-rating-13-1" class="radio-label"></label>
                </div>
                Купили недавно такие на Вашем сайте, нужно было в качестве студийного света. Очень довольны, светит хорошо, свет белый, все как надо. Купили недавно такие на Вашем сайте, нужно было в качестве студийного света. Очень довольны, светит хорошо, свет белый, все как надо </div>
        </div>
    </div>
</div>
<div class="row row-margin">
    <div class="col-md-12">
        <div class="form-group">
            <a class="btn btn-sm yellow btn-width" href="catalog.html">
                <i class="icon icon-arrows_left left-pull"></i>
                вернуться в каталог
            </a>
        </div>
    </div>
</div>
