<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:57 PM
 */
?>

<div class="portfolio-article">
        <div class="cbp-item ">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-1.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">Косметический ремонт квартиры: основные правила</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Как сделать ремонт недорого?
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://gost.kiev.ua/">http://gost.kiev.ua/</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>

        <div class="cbp-item">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-2.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">недорогой качественный ремонт</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Как сделать недорогой и красивый ремонт?
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://vopros-remont.ru/">http://vopros-remont.ru/</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>

        <div class="cbp-item">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-3.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">Освещение для магазина</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Торговое освещение помогает увеличить продажи: выбирайте правильное освещение для магазина
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://www.merchandising.by/articles/articles-01.html">http://www.merchandising.by/articles/articles-01.html</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>

        <div class="cbp-item">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-4.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">дизайн комнаты для подростка</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Как сделать ремонт недорого?
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://gost.kiev.ua/">http://gost.kiev.ua/</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>

        <div class="cbp-item">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-5.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">дизайн комнаты маленького размера</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Как сделать недорогой и красивый ремонт?
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://vopros-remont.ru/">http://vopros-remont.ru/</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>

        <div class="cbp-item">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>tmp/images/galery-img-6.jpg" alt="">
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="">экоомия энергоресурсов</a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    08.04.2016
                </div>
                <div class="txt-question">
                    Торговое освещение помогает увеличить продажи: выбирайте правильное освещение для магазина
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://www.merchandising.by/articles/articles-01.html">http://www.merchandising.by/articles/articles-01.html</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> 265
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>
</div>
