<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:57 PM
 */
?>
<?php
$_product = Mage::registry('current_product');
$_categoryIds = $_product->getCategoryIds();
foreach($_categoryIds as $_categoryId) {
    //$postIds[$_categoryId] = $this->getPostModel()->getRelatedPost($_categoryId);
    $postIds = $this->getPostm()->getRelatedPostIds($_categoryId);
}
//Zend_Debug::dump($postIds);

//Zend_Debug::dump($this->getPosts($postIds));
?>
<?php $_posts = $this->getPosts($postIds); ?>

<div class="portfolio-article">
    <?php foreach($_posts as $_post):?>
        <div class="cbp-item ">
            <div class="cbp-caption">
                <div class="cbp-caption-defaultWrap">
                    <?php if ($_post->getImage()) : ?>
                        <img src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image')->resize(400); ?>"
                             alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>">
                    <?php endif; ?>
                </div>
            </div>
            <div class="cb-min-height">
                <div class="cbp-l-grid-projects-title">
                    <a href="<?php echo $_post->getPostUrl() ?>"><?php echo $_post->getPostTitle(); ?></a>
                </div>
                <div class="cbp-l-grid-projects-desc txt-data">
                    <?php echo $_post->getData('created_at')?>
                </div>
                <div class="txt-question">
                    <?php echo $_post->getPostExcerpt(); ?>
                </div>
                <div class="margin-cbp">
                    <span class="bold">Источник:</span> <a href="http://gost.kiev.ua/">http://gost.kiev.ua/</a>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Просмотров:</span> <?php echo $_post->getViews(); ?>
                </div>
                <div class="cbp-l-grid-projects-desc cbp-min">
                    <span class="bold">Комментариев:</span> 0
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
