<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 11/14/16
 * Time: 2:59 PM
 */
?>

<div class="table-responsive">
    <table class="table table-bordered table-middle table-padding">
        <thead>
        <tr>
            <th><?php echo $this->__('Supplier')?></th>
            <th><?php echo $this->__('Price')?></th>
            <th><?php echo $this->__('Rating')?></th>
            <th><?php echo $this->__('Availability')?></th>
            <th><?php echo $this->__('Topicality')?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td> Upper </td>
            <td>2 240</td>
            <td>
                <div class="stars-rating">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-16-5">
                    <label for="star-rating-16-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-16-4">
                    <label for="star-rating-16-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-16-3">
                    <label for="star-rating-16-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-16-2">
                    <label for="star-rating-16-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-16-1">
                    <label for="star-rating-16-1" class="radio-label"></label>
                </div>
            </td>
            <td>в наличии</td>
            <td>
                <div class="stars-rating">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-17-5">
                    <label for="star-rating-17-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-17-4">
                    <label for="star-rating-17-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-17-3">
                    <label for="star-rating-17-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-17-2">
                    <label for="star-rating-17-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-17-1">
                    <label for="star-rating-17-1" class="radio-label"></label>
                </div>
            </td>
        </tr>
        <tr>
            <td> Upper </td>
            <td>2 240</td>
            <td>
                <div class="stars-rating">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-18-5">
                    <label for="star-rating-18-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-18-4">
                    <label for="star-rating-18-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-18-3">
                    <label for="star-rating-18-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-18-2">
                    <label for="star-rating-18-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-18-1">
                    <label for="star-rating-18-1" class="radio-label"></label>
                </div>
            </td>
            <td>в наличии</td>
            <td>
                <div class="stars-rating">
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-19-5">
                    <label for="star-rating-19-5" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-19-4">
                    <label for="star-rating-19-4" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-19-3">
                    <label for="star-rating-19-3" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-19-2">
                    <label for="star-rating-19-2" class="radio-label"></label>
                    <input type="radio" disabled="disabled" checked="checked" name="star-rating-19-1">
                    <label for="star-rating-19-1" class="radio-label"></label>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
