<?php
/**
 * Created by PhpStorm.
 * User: nick
 * Date: 12/2/16
 * Time: 8:35 PM
 */


$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

foreach($children as $category){
    $html .= sprintf("%s (%d)\n", $category->getName(), $category->getProductCount());
    if($category->hasChildren()){
        $html .= $this->render($category, $parentLevel);
    }
}

return $html;