<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 2/2/17
 * Time: 4:48 PM
 */
?>
<?php
$_block = $this;
/* @var $_block Stableflow_UserManual_Block_Adminhtml_Catalog_Product_Manual */
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo Mage::helper('user_manual')->__('user_manual'); ?>
                </li>
            </ul>
        </li>
    </ul>
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid" width="100%">
            <col width="1" />
            <col width="150"/>
            <col width="150" />
            <col width="70" />
            <col width="70" />
            <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('user_manual')->__('N') ?></th>
                <th><?php echo Mage::helper('user_manual')->__('File') ?></th>
                <th><?php echo Mage::helper('user_manual')->__('Label') ?></th>
                <th><?php echo Mage::helper('user_manual')->__('Sort Order') ?></th>
                <th class="last"><?php echo Mage::helper('user_manual')->__('Remove') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
            <?php foreach($this->getManual() as $row): ?>
                <tr id="<?php echo $_block->getHtmlId() ?>_default">
                    <td>&nbsp;</td>
                    <td><?php echo $row['file']; ?></td>
                    <td><?php echo $row['label']; ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            <?php endforeach ;?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="100" class="last" style="padding:8px">
                    <?php echo $_block->getUploaderHtml() ?>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
    <input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="[user_manual][images]" value="<?php echo $_block->escapeHtml($_block->getImagesJson()) ?>" />
    <input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="[user_manual][values]" value="<?php echo $_block->escapeHtml($_block->getImagesValuesJson()) ?>" />
