<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/29/16
 * Time: 12:32 PM
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    //var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body ">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="timeline timeline-product">
                <!-- TIMELINE ITEM -->
                <?php echo $this->getChildHtml('media') ?>
                <div class="timeline-body clearfix">
                    <div class="timeline-body-head">
                        <div class="timeline-body-head-caption">
                            <a class="timeline-body-title font-blue-madison" href="javascript:;"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </div>
                    </div>
                    <!-- product-view-rating.phtml -->
                    <?php echo $this->getChildHtml('product-rating') ?>
                    <div class="timeline-body-content">
                        <p class="timeline-conten-min-width txt-link margin-bottom-lg">Вы можете заказать товар прямо сейчас на нашем сайте! Наши специалисты подберут то, что Вас интересует по минимальной цене и с минимальной стоимостью доставки специально для Вас!</p>
                        <?php if ($_product->getShortDescription()):?>
                            <div class="short-description">
                                <h2><?php echo $this->__('Quick Overview') ?></h2>
                                <p><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
                            </div>
                        <?php endif;?>
                        <div class="row margin-top-biggest">
                            <div class="col-md-6 col-sm-6">
                                <ul class="list-icon-navs">
                                    <li>
                                        <a href=""><i class="icon icon-home"></i>использование в дизайне</a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-photo"></i>3 фото / видео</a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-comments"></i>3 комментария</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6 col-sm-6 text-right">
                                <div class="basket-number basket-number-lg"><?php echo $this->getChildHtml('product_type_data') ?></div>
                                <a href="" class="link-underline">Попросить скидку</a>
                                <div class="clearfix margin-top-min">
                                    <div class="add-to-box">
                                        <?php if($_product->isSaleable()): ?>
                                            <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <!-- END TIMELINE ITEM -->
            </div>

            <div class="tabbable tabbable-tabdrop">
                <ul class="nav nav-tabs">
                    <?php $i = 1; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                        <li class="<?php echo $i == 1 ?  'active' : '' ; ?>">
                            <a href="#tab<?php echo $i;?>" data-toggle="tab" aria-expanded="false"><?php echo $this->escapeHtml($alias); ?></a>
                            <?php if ($title = $this->getChildData($alias, 'title')):?>
                                <!--<a href="#tab<?php echo $i;?>" data-toggle="tab"><?php echo $this->escapeHtml($title); ?></a>-->
                            <?php endif;?>
                            <?php $html_render .= '<div class="tab-pane ' . ($i == 1 ?  'active"' : '"') .  ' id="tab'. $i .'">'.$html.'</div>'; $i++;?>
                        </li>
                    <?php endforeach;?>
                </ul>
                <div class="tab-content">
                    <?php echo $html_render; ?>
                </div>
            </div>

            
        </form>

        <div class="modal fade draggable-modal" id="modal_product" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog modal-dialog-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    </div>
                    <div class="modal-body clearfix">
                        <div class="title-slider clearfix">
                            <h4 class="modal-title"><?php echo $this->escapeHtml($_product->getName());?></h4>
                        </div>
                        <ul class="menu-slider display-inline">
                            <!--<li class="active"><a href="">Все (3)</a></li>
                            <li><a href="">Фото (2)</a></li>
                            <li><a href="">Видео (1)</a></li>-->
                        </ul>
                        <ul class="pgwSlider">
                            <?php foreach($_product->getMediaGalleryImages() as $_image):?>
                                <li><img src="<?php echo $_image->getUrl();?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" ></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('#modal_product').on('shown.bs.modal', function() {
                    jQuery('.pgwSlider').pgwSlider({
                        autoSlide: false,
                        displayControls: true
                    });
                })

            });
        </script>
        <script type="text/javascript">
            //<![CDATA[
            jQuery(document).ready(function() {
                console.log('asdasd');
                jQuery('#js-grid-lightbox-gallery').cubeportfolio({
                    filters: '#js-filters-lightbox-gallery1, #js-filters-lightbox-gallery2',
                    loadMore: '#js-loadMore-lightbox-gallery',
                    loadMoreAction: 'click',
                    layoutMode: 'grid',
                    mediaQueries: [
                        {   width: 1500,
                            cols: 5
                        }, {
                            width: 1100,
                            cols: 4
                        }, {
                            width: 800,
                            cols: 3
                        }, {
                            width: 480,
                            cols: 2
                        }, {
                            width: 320,
                            cols: 1
                        }
                    ],
                    defaultFilter: '*',
                    animationType: 'rotateSides',
                    gapHorizontal: 10,
                    gapVertical: 10,
                    gridAdjustment: 'responsive',
                    caption: 'zoom',
                    displayType: 'default',
                    displayTypeSpeed: 100,

                    // lightbox
                    lightboxDelegate: '.cbp-lightbox',
                    lightboxGallery: true,
                    lightboxTitleSrc: 'data-title',
                    lightboxCounter: '<div class="cbp-popup-lightbox-counter">{{current}} of {{total}}</div>',

                    // singlePageInline
                    singlePageInlineDelegate: '.cbp-singlePageInline',
                    singlePageInlinePosition: 'below',
                    singlePageInlineInFocus: true,
                    singlePageInlineCallback: function(url, element) {
                        // to update singlePageInline content use the following method: this.updateSinglePageInline(yourContent)
                        var t = this;

                        jQuery.ajax({
                            url: url,
                            type: 'GET',
                            dataType: 'html',
                            timeout: 10000
                        })
                            .done(function(result) {

                                t.updateSinglePageInline(result);

                            })
                            .fail(function() {
                                t.updateSinglePageInline('AJAX Error! Please refresh the page!');
                            });
                    }
                });
            });
            //]]>
        </script>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>
</div>