<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/29/16
 * Time: 12:32 PM
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    //var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body ">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="timeline timeline-product">
                <!-- TIMELINE ITEM -->
                <?php echo $this->getChildHtml('media') ?>
                <div class="timeline-body clearfix">
                    <div class="timeline-body-head">
                        <div class="timeline-body-head-caption">
                            <a class="timeline-body-title font-blue-madison" href="javascript:;"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name');?></a>
                        </div>
                    </div>
                    <!-- product-view-rating.phtml -->
                    <?php echo $this->getChildHtml('product-rating') ?>
                    <div class="timeline-body-content">
                        <p class="timeline-conten-min-width txt-link margin-bottom-lg"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_view_notice')->toHtml();?> </p>
                        <?php if ($_product->getShortDescription()):?>
                            <div class="short-description">
                                <h2><?php echo $this->__('Quick Overview') ?></h2>
                                <p><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
                            </div>
                        <?php endif;?>
                        <div class="row margin-top-biggest">
                            <div class="col-md-6 col-sm-6">
                                <ul class="list-icon-navs">
                                    <li>
                                        <a href=""><i class="icon icon-home"></i><?php echo $this->__('Use in the design')?></a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-photo"></i><?php echo $this->__('Photo / Video')?></a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-comments"></i><?php echo $this->__('Comment`s')?></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6 col-sm-6 text-right">
                                <div class="basket-number basket-number-lg"><?php echo $this->getChildHtml('product_type_data') ?></div>
                                <a href="" class="link-underline"><?php echo $this->__('Ask for discount')?></a>
                                <div class="clearfix margin-top-min">
                                    <div class="add-to-box">
                                        <?php if($_product->isSaleable()): ?>
                                            <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END TIMELINE ITEM -->
            </div>
        </form>
        <!-- Tabs content -->
        <div class="tabbable tabbable-tabdrop">
            <div id="tabs">
                <ul class="nav nav-tabs">
                    <?php $i = 1; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                        <li>
                            <a href="#tabs-<?php echo $i;?>"><?php echo $this->escapeHtml($alias); ?></a>
                            <?php $html_render .= '<div id="tabs-'. $i . '">' .  $html . '</div>'; $i++;?>
                        </li>
                    <?php endforeach;?>
                </ul>
                <?php echo $html_render; ?>
            </div>
              <script  type="text/javascript">
                  jQuery(document).ready(function(){
                    jQuery( "#tabs" ).tabs();
                  });
             </script>
        </div>
        <!-- END Tabs content -->
        <div class="modal fade draggable-modal" id="modal_product" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog modal-dialog-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close close-default" data-dismiss="modal" aria-hidden="true"><i class="icon icon-cancel-music"></i></button>
                    </div>
                    <div class="modal-body clearfix">
                        <div class="title-slider clearfix">
                            <h4 class="modal-title"><?php echo $this->escapeHtml($_product->getName());?></h4>
                        </div>
                        <ul class="menu-slider display-inline">
                            <li class="active"><a href=""><?php echo $this->__('All')?></a></li>
                            <li><a href=""><?php echo $this->__('Photo')?></a></li>
                            <li><a href=""><?php echo $this->__('Video')?></a></li>
                        </ul>
                        <ul class="pgwSlider">
                            <?php foreach($_product->getMediaGalleryImages() as $_image):?>
                                <li><img src="<?php echo $_image->getUrl();?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" ></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('#modal_product').on('shown.bs.modal', function() {
                    jQuery('.pgwSlider').pgwSlider({
                        autoSlide: false,
                        displayControls: true
                    });
                })

            });
        </script>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>
</div>