<?php
/**
 * Created by PhpStorm.
 * User: nick
 * Date: 12/6/16
 * Time: 9:47 PM
 */
?>
<?php $_posts = $this->getPosts(); ?>
<h3 class="page-title post-title">
    <?php if (Mage::helper('mageplaza_betterblog/post')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('mageplaza_betterblog/post')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('mageplaza_betterblog')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <?php echo Mage::helper('mageplaza_betterblog')->__('Posts') ?>
</h3>
<?php if ($_posts->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="portlet light portlet-fit bordered">
        <div class="portlet-body">
            <div class="row">
                <div class="col-md-9 col-sm-9 col-news">
                    <?php $postColumn = 2 ; $i = 1; ?>
                    <?php foreach($_posts as $_post):?>
                        <?php echo ($i == 1) ? '<div class="row media-list">' : ''?>
                            <div class="col-md-6 col-sm-6">
                                <div class="media">
                                    <div class="media-left">
                                        <?php if ($_post->getImage()) : ?>
                                            <a href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $_post->getPostTitle(); ?>">
                                                <img class="media-object"
                                                     src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image')->resize(100); ?>"
                                                     alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>"/>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            <a href="<?php echo $_post->getPostUrl() ?>">
                                                <?php echo $_post->getPostTitle(); ?>
                                            </a>
                                            <span class="media-date"><?php echo $_post->getData('created_at')?></span>
                                        </h4>
                                        <?php echo $_post->getPostExcerpt(); ?><a href="<?php echo $_post->getPostUrl() ?>"> <?php echo $this->__('[...]'); ?></a>
                                    </div>
                                </div>
                            </div>
                        <?php if ($i++ == $postColumn): ?>
                            </div>
                            <?php $i = 1; ?>
                        <?php endif?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <div class="post-list-container">
    <?php echo Mage::helper('mageplaza_betterblog')->__('There are no posts at this moment'); ?>
    </div><?php endif;?>
