<?php
/**
 * Mageplaza_BetterBlog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post comments list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 */
?>
<?php $_post = $this->getPost()?>
<?php if ($_post->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <div class="box-collateral box-reviews" id="post-reviews">
            <h2 class="border-top"><?php echo $this->__('Comments') ?></h2>

            <div class="media-list">
            <?php foreach ($_comments as $_comment):?>
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <span class="c-date"><?php echo $this->formatDate($_comment->getCreatedAt(), 'long' );?></span>
                            <span class="author">
                                <?php echo $this->__('User %s wrote:', $this->escapeHtml($_comment->getName()))?>                             
                            </span>                            
                        </h4>
                        <p><strong><?php echo $this->escapeHtml($_comment->getTitle()) ?></strong></p>
                        <?php echo nl2br($this->escapeHtml($_comment->getComment())) ?>
                    </div>
                </div>
            <?php endforeach; ?>               
            </div>

            <?php echo $this->getPagerHtml() ?>
        </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif;?>
