
<?php $_width=$this->getImageWidth() ?>
<div class="portfolio-content">
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
                <a href="<?php echo $_image->getUrl();?>" class="flipLightBox">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(225); ?>" width="225" height="225" alt="<?php echo $this->escapeHtml($_image->getLabel());?>" />
                    <span><b><?php echo $this->escapeHtml($_image->getLabel());?></b><br />image</span>
                </a>
            <?php endif; ?>
            <?php $i++; endforeach; ?>
    <?php endif; ?>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.portfolio-content').flipLightBox({
            lightbox_text_status: 0,
            lightbox_navigation_status: 0
        })
    });
</script>

