
<?php $_width=$this->getImageWidth() ?>
<div class="portfolio-content portfolio-3">
    <?php foreach($this->getGalleryCollection() as $_image):?>
        <?php //print_r($_image);?>
        <div id="js-grid-lightbox-gallery" class="cbp">
            <div class="cbp-item web-design graphic print motion">
                <a href="" class="cbp-caption cbp-singlePageInline" rel="nofollow">
                    <div class="cbp-caption-defaultWrap">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getImageFile()); ?>"
                            <?php if($_width): ?>
                                width="<?php echo $_width ?>"
                            <?php endif; ?>
                             alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
                             title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"
                             id="product-gallery-image" class="image" />
                    </div>
                </a>
            </div>
        </div>
    <?php endforeach ?>
</div>
<div class="row row-margin">
    <div class="col-md-12">
        <div class="form-group">
            <a class="btn btn-sm yellow btn-width" href="catalog.html">
                <i class="icon icon-arrows_left left-pull"></i>
                вернуться в каталог
            </a>
        </div>
    </div>
</div>
