
<?php $_width=$this->getImageWidth() ?>
<div class="portfolio-content">
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
                <a href="<?php echo $_image->getUrl();?>" class="flipLightBox">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(225); ?>" width="225" height="225" alt="<?php echo $this->escapeHtml($_image->getLabel());?>" />
                    <span><b><?php echo $this->escapeHtml($_image->getLabel());?></b><br />image</span>
                </a>
            <?php endif; ?>
            <?php $i++; endforeach; ?>
    <?php endif; ?>
</div>
<div class="row row-margin">
    <div class="col-md-12">
        <div class="form-group">
            <a class="btn btn-sm yellow btn-width" href="catalog.html">
                <i class="icon icon-arrows_left left-pull"></i>
                <?php echo $this->__('Back to catalog');?>
            </a>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('body').flipLightBox({
            lightbox_text_status: 0,
            lightbox_navigation_status: 0
        })
    });
</script>

<!--
<div class="portfolio-content portfolio-3">
    <?php /*foreach($this->getGalleryCollection() as $_image):*/?>
        <?php /*//print_r($_image);*/?>
        <div id="js-grid-lightbox-gallery" class="cbp">
            <div class="cbp-item web-design graphic print motion">
                <a href="" class="cbp-caption cbp-singlePageInline" rel="nofollow">
                    <div class="cbp-caption-defaultWrap">
                        <img src="<?php /*echo $_image->getUrl(); //echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getImageFile()); */?>"
                            <?php /*if($_width): */?> width="<?php /*echo $_width */?>"<?php /*endif; */?>
                             alt="<?php /*echo $this->escapeHtml($_image->getLabel()) */?>"
                             title="<?php /*echo $this->escapeHtml($_image->getLabel()) */?>"
                             id="product-gallery-image" class="image" />
                    </div>
                </a>
            </div>
        </div>
    <?php /*endforeach */?>
</div>-->
