<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 7/29/16
 * Time: 12:32 PM
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    //var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="portlet light portlet-fit bordered">
    <div class="portlet-title"></div>
    <div class="portlet-body ">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="timeline timeline-product">
                <!-- TIMELINE ITEM -->
                <div class="timeline-badge">
                    <?php echo $this->getChildHtml('media') ?>
                </div>
                <div class="timeline-body clearfix">
                    <div class="timeline-body-head">
                        <div class="timeline-body-head-caption">
                            <a class="timeline-body-title font-blue-madison" href="javascript:;"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name');?></a>
                        </div>
                    </div>
                    <!-- product-view-rating.phtml -->
                    <div class="timeline-btn-product display-inline">
                        <div class="btn yellow-mint btn-outline min-width" data-product-name="<?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name')?>" data-toggle="modal" href="#draggable"><?php echo $this->__('Ask question')?></div>
                        <?php echo $this->getChildHtml('product-rating') ?>
                    </div>
                        <div class="timeline-body-content">
                        <div class="timeline-conten-min-width txt-link margin-bottom-lg"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_view_notice')->toHtml();?> </div>
                        <?php if (null && $_product->getShortDescription()):?>
                            <div class="short-description">
                                <h2><?php echo $this->__('Quick Overview') ?></h2>
                                <p><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
                            </div>
                        <?php endif;?>
                        <?php echo $this->getChildHtml('attributes');?>
                        <div class="row margin-top-biggest">
                            <div class="col-md-6 col-sm-6">
                                <!--<ul class="list-icon-navs">
                                    <li>
                                        <a href=""><i class="icon icon-home"></i><?php /*echo $this->__('Use in the design')*/?></a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-photo"></i><?php /*echo $this->__('Photo / Video')*/?></a>
                                    </li>
                                    <li>
                                        <a href=""><i class="icon icon-comments"></i><?php /*echo $this->__('Comment`s')*/?></a>
                                    </li>
                                </ul>-->
                            </div>
                            <div class="col-md-6 col-sm-6 text-right">
                                <div class="basket-number basket-number-lg"><?php echo $this->getChildHtml('product_type_data') ?></div>
                                <a data-toggle="modal" data-product-name="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name')?>" href="#draggable" class="link-underline"><?php echo $this->__('Ask for discount')?></a>
                                <div class="clearfix margin-top-min">
                                    <div class="add-to-box">
                                        <?php if($_product->isSaleable()): ?>
                                            <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END TIMELINE ITEM -->
            </div>
        </form>
        <!-- Tabs content -->
        <div class="tabbable tabbable-tabdrop">
            <div id="tabs">
                <ul class="nav nav-tabs">
                    <?php $i = 1; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $groupTab => $html):?>
                        <li>
                            <?php
                            if ($title = $this->getChildData($groupTab, 'title'));
                            else
                                $title = $groupTab;
                            ?>
                            <a href="#tabs-<?php echo $i;?>"><?php echo $this->escapeHtml($title); ?></a>
                            <?php $html_render .= '<div id="tabs-'. $i . '">' .  $html . '</div>'; $i++;?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="tab-content">
                    <?php echo $html_render; ?>
                </div>
            </div>
            <script  type="text/javascript">
                //<![CDATA[
                jQuery(document).ready(function(){
                    jQuery( "#tabs" ).tabs();
                });
                //]]>
            </script>
        </div>
        <!-- END Tabs content -->
        <div class="row row-margin">
            <div class="col-md-12">
                <div class="form-group">
                    <a class="btn btn-sm yellow btn-width" href="<?php echo Mage::getModel('catalog/category')->load($_product->getCategoryIds()[0])->getUrl();?>">
                        <i class="icon icon-arrows_left left-pull"></i>
                        <?php echo $this->__('Back to catalog');?>
                    </a>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>
</div>