<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 6/9/17
 * Time: 12:44 PM
 */
?>

<div id="ajaxnotice" style="display:none">
    <div class="ajaxnotice_inner">
        <div id="ajaxnotice_working">
            <img src="<?php echo $this->getSkinUrl('images/sf_ajaxcart/loading.gif'); ?>" alt="" />
        </div>
        <div id="ajaxnotice_result"></div>
        <div class="ajaxnotice_clearer"></div>
    </div>
</div>